# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\"L\n\x0cSetPidParams\x12\x18\n\x06target\x18\x01 \x01(\x0e\x32\x08.PidType\x12\n\n\x02kp\x18\x02 \x01(\x02\x12\n\n\x02ki\x18\x03 \x01(\x02\x12\n\n\x02kd\x18\x04 \x01(\x02\"(\n\x0cGetPidParams\x12\x18\n\x06target\x18\x01 \x01(\x0e\x32\x08.PidType\"c\n\x11GetPidParamsReply\x12\x18\n\x06target\x18\x01 \x01(\x0e\x32\x08.PidType\x12\n\n\x02kp\x18\x02 \x01(\x02\x12\n\n\x02ki\x18\x03 \x01(\x02\x12\n\n\x02kd\x18\x04 \x01(\x02\x12\x10\n\x08setpoint\x18\x05 \x01(\x02\"<\n\x0eSetPidSetpoint\x12\x18\n\x06target\x18\x01 \x01(\x0e\x32\x08.PidType\x12\x10\n\x08setpoint\x18\x02 \x01(\x02\"j\n\x0cPidTelemetry\x12\x18\n\x06target\x18\x01 \x01(\x0e\x32\x08.PidType\x12\t\n\x01p\x18\x02 \x01(\x02\x12\t\n\x01i\x18\x03 \x01(\x02\x12\t\n\x01\x64\x18\x04 \x01(\x02\x12\x10\n\x08integral\x18\x05 \x01(\x02\x12\r\n\x05\x65rror\x18\x06 \x01(\x02\"\xe9\x01\n\rConfigMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12(\n\x0fset_pid_paramsp\x18\x02 \x01(\x0b\x32\r.SetPidParamsH\x00\x12(\n\x0fget_pid_paramsp\x18\x03 \x01(\x0b\x32\r.GetPidParamsH\x00\x12\x33\n\x15get_pid_params_replyp\x18\x04 \x01(\x0b\x32\x12.GetPidParamsReplyH\x00\x12,\n\x11set_pid_setpointp\x18\x05 \x01(\x0b\x32\x0f.SetPidSetpointH\x00\x42\t\n\x07payload\"X\n\x10TelemetryMessage\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\'\n\x0epid_telemetryp\x18\x02 \x01(\x0b\x32\r.PidTelemetryH\x00\x42\t\n\x07payload*?\n\x07PidType\x12\x0b\n\x07\x42\x41LANCE\x10\x00\x12\t\n\x05SPEED\x10\x01\x12\x0c\n\x08POSITION\x10\x02\x12\x0e\n\nWHEEL_TRIM\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PIDTYPE']._serialized_start=732
  _globals['_PIDTYPE']._serialized_end=795
  _globals['_SETPIDPARAMS']._serialized_start=15
  _globals['_SETPIDPARAMS']._serialized_end=91
  _globals['_GETPIDPARAMS']._serialized_start=93
  _globals['_GETPIDPARAMS']._serialized_end=133
  _globals['_GETPIDPARAMSREPLY']._serialized_start=135
  _globals['_GETPIDPARAMSREPLY']._serialized_end=234
  _globals['_SETPIDSETPOINT']._serialized_start=236
  _globals['_SETPIDSETPOINT']._serialized_end=296
  _globals['_PIDTELEMETRY']._serialized_start=298
  _globals['_PIDTELEMETRY']._serialized_end=404
  _globals['_CONFIGMESSAGE']._serialized_start=407
  _globals['_CONFIGMESSAGE']._serialized_end=640
  _globals['_TELEMETRYMESSAGE']._serialized_start=642
  _globals['_TELEMETRYMESSAGE']._serialized_end=730
# @@protoc_insertion_point(module_scope)
