/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "robot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetPidParams, SetPidParams, AUTO)


PB_BIND(GetPidParams, GetPidParams, AUTO)


PB_BIND(GetPidParamsReply, GetPidParamsReply, AUTO)


PB_BIND(SetPidSetpoint, SetPidSetpoint, AUTO)


PB_BIND(PidTelemetry, PidTelemetry, AUTO)


PB_BIND(ConfigMessage, ConfigMessage, AUTO)


PB_BIND(TelemetryMessage, TelemetryMessage, AUTO)





