/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROBOT_PB_H_INCLUDED
#define PB_ROBOT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _PidType {
    PidType_BALANCE = 0,
    PidType_SPEED = 1,
    PidType_POSITION = 2,
    PidType_WHEEL_TRIM = 3
} PidType;

/* Struct definitions */
/* Message to set all PID tuning values for a certain pid */
typedef struct _SetPidParams {
    PidType target;
    float kp;
    float ki;
    float kd;
} SetPidParams;

/* Message to get all PID tuning values for a certain pid */
typedef struct _GetPidParams {
    PidType target;
} GetPidParams;

/* Reply message to a get_pid_config message */
typedef struct _GetPidParamsReply {
    PidType target;
    float kp;
    float ki;
    float kd;
    float setpoint;
} GetPidParamsReply;

/* Message to change the setpoint of a certain pid */
typedef struct _SetPidSetpoint {
    PidType target;
    float setpoint;
} SetPidSetpoint;

typedef struct _PidTelemetry {
    PidType target;
    float p;
    float i;
    float d;
    float integral;
    float error;
} PidTelemetry;

/* Messages that should be acked and maybe in the future encrypted or authenticated */
typedef struct _ConfigMessage {
    /* Used for ACKs and responses */
    uint32_t transaction_id;
    pb_size_t which_payload;
    union {
        SetPidParams set_pid_paramsp;
        GetPidParams get_pid_paramsp;
        GetPidParamsReply get_pid_params_replyp;
        SetPidSetpoint set_pid_setpointp;
    } payload;
} ConfigMessage;

typedef struct _TelemetryMessage {
    /* Used to find out how many packets are getting dropped */
    uint32_t sequence;
    pb_size_t which_payload;
    union {
        PidTelemetry pid_telemetryp;
    } payload;
} TelemetryMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PidType_MIN PidType_BALANCE
#define _PidType_MAX PidType_WHEEL_TRIM
#define _PidType_ARRAYSIZE ((PidType)(PidType_WHEEL_TRIM+1))

#define SetPidParams_target_ENUMTYPE PidType

#define GetPidParams_target_ENUMTYPE PidType

#define GetPidParamsReply_target_ENUMTYPE PidType

#define SetPidSetpoint_target_ENUMTYPE PidType

#define PidTelemetry_target_ENUMTYPE PidType




/* Initializer values for message structs */
#define SetPidParams_init_default                {_PidType_MIN, 0, 0, 0}
#define GetPidParams_init_default                {_PidType_MIN}
#define GetPidParamsReply_init_default           {_PidType_MIN, 0, 0, 0, 0}
#define SetPidSetpoint_init_default              {_PidType_MIN, 0}
#define PidTelemetry_init_default                {_PidType_MIN, 0, 0, 0, 0, 0}
#define ConfigMessage_init_default               {0, 0, {SetPidParams_init_default}}
#define TelemetryMessage_init_default            {0, 0, {PidTelemetry_init_default}}
#define SetPidParams_init_zero                   {_PidType_MIN, 0, 0, 0}
#define GetPidParams_init_zero                   {_PidType_MIN}
#define GetPidParamsReply_init_zero              {_PidType_MIN, 0, 0, 0, 0}
#define SetPidSetpoint_init_zero                 {_PidType_MIN, 0}
#define PidTelemetry_init_zero                   {_PidType_MIN, 0, 0, 0, 0, 0}
#define ConfigMessage_init_zero                  {0, 0, {SetPidParams_init_zero}}
#define TelemetryMessage_init_zero               {0, 0, {PidTelemetry_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SetPidParams_target_tag                  1
#define SetPidParams_kp_tag                      2
#define SetPidParams_ki_tag                      3
#define SetPidParams_kd_tag                      4
#define GetPidParams_target_tag                  1
#define GetPidParamsReply_target_tag             1
#define GetPidParamsReply_kp_tag                 2
#define GetPidParamsReply_ki_tag                 3
#define GetPidParamsReply_kd_tag                 4
#define GetPidParamsReply_setpoint_tag           5
#define SetPidSetpoint_target_tag                1
#define SetPidSetpoint_setpoint_tag              2
#define PidTelemetry_target_tag                  1
#define PidTelemetry_p_tag                       2
#define PidTelemetry_i_tag                       3
#define PidTelemetry_d_tag                       4
#define PidTelemetry_integral_tag                5
#define PidTelemetry_error_tag                   6
#define ConfigMessage_transaction_id_tag         1
#define ConfigMessage_set_pid_paramsp_tag        2
#define ConfigMessage_get_pid_paramsp_tag        3
#define ConfigMessage_get_pid_params_replyp_tag  4
#define ConfigMessage_set_pid_setpointp_tag      5
#define TelemetryMessage_sequence_tag            1
#define TelemetryMessage_pid_telemetryp_tag      2

/* Struct field encoding specification for nanopb */
#define SetPidParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    kp,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    ki,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    kd,                4)
#define SetPidParams_CALLBACK NULL
#define SetPidParams_DEFAULT NULL

#define GetPidParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1)
#define GetPidParams_CALLBACK NULL
#define GetPidParams_DEFAULT NULL

#define GetPidParamsReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    kp,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    ki,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    kd,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    setpoint,          5)
#define GetPidParamsReply_CALLBACK NULL
#define GetPidParamsReply_DEFAULT NULL

#define SetPidSetpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    setpoint,          2)
#define SetPidSetpoint_CALLBACK NULL
#define SetPidSetpoint_DEFAULT NULL

#define PidTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    target,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    p,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    i,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    d,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    integral,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    error,             6)
#define PidTelemetry_CALLBACK NULL
#define PidTelemetry_DEFAULT NULL

#define ConfigMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transaction_id,    1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_pid_paramsp,payload.set_pid_paramsp),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_pid_paramsp,payload.get_pid_paramsp),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_pid_params_replyp,payload.get_pid_params_replyp),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_pid_setpointp,payload.set_pid_setpointp),   5)
#define ConfigMessage_CALLBACK NULL
#define ConfigMessage_DEFAULT NULL
#define ConfigMessage_payload_set_pid_paramsp_MSGTYPE SetPidParams
#define ConfigMessage_payload_get_pid_paramsp_MSGTYPE GetPidParams
#define ConfigMessage_payload_get_pid_params_replyp_MSGTYPE GetPidParamsReply
#define ConfigMessage_payload_set_pid_setpointp_MSGTYPE SetPidSetpoint

#define TelemetryMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pid_telemetryp,payload.pid_telemetryp),   2)
#define TelemetryMessage_CALLBACK NULL
#define TelemetryMessage_DEFAULT NULL
#define TelemetryMessage_payload_pid_telemetryp_MSGTYPE PidTelemetry

extern const pb_msgdesc_t SetPidParams_msg;
extern const pb_msgdesc_t GetPidParams_msg;
extern const pb_msgdesc_t GetPidParamsReply_msg;
extern const pb_msgdesc_t SetPidSetpoint_msg;
extern const pb_msgdesc_t PidTelemetry_msg;
extern const pb_msgdesc_t ConfigMessage_msg;
extern const pb_msgdesc_t TelemetryMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetPidParams_fields &SetPidParams_msg
#define GetPidParams_fields &GetPidParams_msg
#define GetPidParamsReply_fields &GetPidParamsReply_msg
#define SetPidSetpoint_fields &SetPidSetpoint_msg
#define PidTelemetry_fields &PidTelemetry_msg
#define ConfigMessage_fields &ConfigMessage_msg
#define TelemetryMessage_fields &TelemetryMessage_msg

/* Maximum encoded size of messages (where known) */
#define ConfigMessage_size                       30
#define GetPidParamsReply_size                   22
#define GetPidParams_size                        2
#define PidTelemetry_size                        27
#define ROBOT_PB_H_MAX_SIZE                      TelemetryMessage_size
#define SetPidParams_size                        17
#define SetPidSetpoint_size                      7
#define TelemetryMessage_size                    35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
